project:
  type: book
  output-dir: docs

book:
  title: "Curso: De las APIs a los gráficos: explorando datos sociales con R"
  author: "Ana Escoto"
  date: "1/19/2026"
  site-url: https://aniuxa.github.io/r_api2026/
  repo-url: https://github.com/aniuxa/r_api2026/
  repo-branch: main
  repo-actions: [edit, issue]  
  chapters:
    - index.qmd
    - install.qmd
    - part: "Teoría"
      chapters:
      - D1.qmd
    - part: "Práctica"
      chapters:
      - P1.qmd
      - P2.qmd
      - P3.qmd
      - P4.qmd
      - P5.qmd
    - videos.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: cosmo
      dark: darkly

editor: visual

